export const dummyTrips = [
    {
        id: 1,
        title: 'Wisata offroad Sukawan',
        refundable: false,
        meetingPoint: 'Alfamart Jati Asih',
        facilities: ['Tent', 'Lunch', 'Parking Area'],
        location: 'Lembang',
        time: '1 Dec - 31 Dec',
        price: 553000,
        duration: '3D2N',
        image: 'https://static.republika.co.id/uploads/member/images/news/qrqv2fsv0p.jpg',
    },
    {
        id: 2,
        title: 'Wisata offroad Sukawan',
        refundable: true,
        meetingPoint: 'Alfamart Jati Asih',
        facilities: ['Tent', 'Lunch', 'Parking Area'],
        location: 'Lembang',
        time: '1 Dec - 31 Dec',
        price: 553000,
        duration: '3D2N',
        image: 'https://static.republika.co.id/uploads/member/images/news/qrqv2fsv0p.jpg',
    },
    {
        id: 3,
        title: 'Wisata offroad Sukawan',
        refundable: true,
        meetingPoint: 'Alfamart Jati Asih',
        facilities: ['Tent', 'Lunch', 'Parking Area'],
        location: 'Lembang',
        time: '1 Dec - 31 Dec',
        price: 553000,
        duration: '3D2N',
        image: 'https://static.republika.co.id/uploads/member/images/news/qrqv2fsv0p.jpg',
    },
    {
        id: 4,
        title: 'Wisata offroad Sukawan',
        refundable: true,
        meetingPoint: 'Alfamart Jati Asih',
        facilities: ['Tent', 'Lunch', 'Parking Area'],
        location: 'Lembang',
        time: '1 Dec - 31 Dec',
        price: 553000,
        duration: '3D2N',
        image: 'https://static.republika.co.id/uploads/member/images/news/qrqv2fsv0p.jpg',
    }
]